FactoryBot.create(:user, email: "user@example.com")

# question1, question2, question3 = FactoryBot.create_list(:question, 3)
# widget1, widget2, widget3 = FactoryBot.create_list(:widget, 3)
#
# FactoryBot.create(:question_widget, question: question1, widget: widget1)
# FactoryBot.create(:question_widget, question: question1, widget: widget2)
# FactoryBot.create(:question_widget, question: question1, widget: widget3)
# FactoryBot.create(:question_widget, question: question2, widget: widget2)
# FactoryBot.create(:question_widget, question: question3, widget: widget3)
#
# test = FactoryBot.create(:test)
#
# survey_question1 = FactoryBot.create(:survey_question, test: test, question: question1, widget: widget1)
# survey_question2 = FactoryBot.create(:survey_question, test: test, question: question2, widget: widget2)
# survey_question3 = FactoryBot.create(:survey_question, test: test, question: question3, widget: widget3)
#
# FactoryBot.create(:way, :right, current_survey_question: survey_question1, next_survey_question: survey_question2)
# FactoryBot.create(:way, :wrong, current_survey_question: survey_question1, next_survey_question: survey_question3)

survey = FactoryBot.create(:survey, name: "Элементы комбинаторики")
FactoryBot.create(:survey, name: "Основные операции над множествами")
FactoryBot.create(:survey, name: "Мощность множества ")
FactoryBot.create(:survey, name: "Основные логические операции (и, или, отрицание)")
FactoryBot.create(:survey, name: "Полином Жегалкина")
FactoryBot.create(:survey, name: "Алгоритм Краскала")
FactoryBot.create(:survey, name: "Эйлеровы пути")
FactoryBot.create(:survey, name: "Гамильтоновы пути")
FactoryBot.create(:survey, name: "Коды Прюфера")
FactoryBot.create(:survey, name: "Положительные и отрицательные степени вершин")
FactoryBot.create(:survey, name: "Изоморфизм ориентированных графов")
FactoryBot.create(:survey, name: "Алгоритм Дейкстры нахождения кратчайшего пути")
FactoryBot.create(:survey, name: "Задача о нахождении максимального потока")
FactoryBot.create(:survey, name: "Алгоритм Форда-Фалкерсона")
FactoryBot.create(:survey, name: "Регулярные выражения")
FactoryBot.create(:survey, name: "Машины Тьюринга")

widget1, widget2, widget3 = FactoryBot.create_list(:widget, 3)

question1 = FactoryBot.create(:question, text: "Сколько трехзначных чисел можно составить из 4 цифр: 1, 2, 3, 4?")
question2 = FactoryBot.create(:question, text: "Сколько двузначных чисел, в которых цифры не повторяются, можно составить из 4 цифр: 1, 2, 3, 4?")
question3 = FactoryBot.create(:question, text: "Сколько пятизначных чисел, в которых цифры не повторяются, можно составить из 6 цифр: 1, 2, 3, 4, 5, 6 ?")
question4 = FactoryBot.create(:question, text: "Сколько двузначных чисел можно составить из 5 цифр: 1, 2, 3, 4, 5?")
question5 = FactoryBot.create(:question, text: "Сколько трехэлементных подмножеств, различающихся хотя бы одним элементом друг от друга и без учета порядка в подмножестве, можно составить из 6 цифр: 1, 2, 3, 4, 5, 6?")
question6 = FactoryBot.create(:question, text: "Сколько будет костей в игре домино, если использовать, только четыре цифры 1, 2, 3, 4?")

survey_question1 = FactoryBot.create(:survey_question, survey: survey, question: question1, widget: widget1)
survey_question2 = FactoryBot.create(:survey_question, survey: survey, question: question2, widget: widget2)
survey_question3 = FactoryBot.create(:survey_question, survey: survey, question: question3, widget: widget3)
survey_question4 = FactoryBot.create(:survey_question, survey: survey, question: question4, widget: widget1)
survey_question5 = FactoryBot.create(:survey_question, survey: survey, question: question5, widget: widget2)
survey_question6 = FactoryBot.create(:survey_question, survey: survey, question: question6, widget: widget3)

FactoryBot.create(:way, :right, current_survey_question: survey_question1, next_survey_question: survey_question3)
FactoryBot.create(:way, :right, current_survey_question: survey_question3, next_survey_question: survey_question5)
FactoryBot.create(:way, :right, current_survey_question: survey_question5, next_survey_question: survey_question6)
FactoryBot.create(:way, :right, current_survey_question: survey_question2, next_survey_question: survey_question4)
FactoryBot.create(:way, :right, current_survey_question: survey_question4, next_survey_question: survey_question6)
FactoryBot.create(:way, :wrong, current_survey_question: survey_question1, next_survey_question: survey_question2)
FactoryBot.create(:way, :wrong, current_survey_question: survey_question2, next_survey_question: survey_question3)
FactoryBot.create(:way, :wrong, current_survey_question: survey_question3, next_survey_question: survey_question4)
FactoryBot.create(:way, :wrong, current_survey_question: survey_question4, next_survey_question: survey_question5)
