defaults: &defaults
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  username: postgres
  password: moskieva

development:
  database: my_answers_dev
  <<: *defaults

test:
  database: my_answers_test
  <<: *defaults

production: &deploy
  <<: *defaults

staging: *deploy
